### ISSUE TITLE
Crash when imageSize > int bounds when listing images

### ISSUE THREAD

**Issue by jpi-stang** [AccelByte/accelbyte-csharp-sdk#1]
`ModelsImageRecord.ImageSize` is an `int` - however, if the size is larger than an int, on deserialization, there's an exception.  Perhaps this should b a `ulong` instead.

**Comment by dhanarab** [comment]
This should be fixed by this commit https://github.com/AccelByte/accelbyte-csharp-sdk/commit/545782f02e9b4e24de3abc6319e21afae882c73e
